import gradio as gr,pandas as pd,numpy as np,joblib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; B=joblib.load(ROOT/"models/final_model.joblib"); MODEL=B["model"]; COLS=B["columns"]; TRAIN=pd.read_csv(ROOT/"data/processed/master_train.csv"); W=pd.read_csv(Path(__file__).parent/"assets/cleaned_weather.csv"); P=pd.read_csv(Path(__file__).parent/"assets/cleaned_prices.csv"); MONTHS=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]; NUM={m:i+1 for i,m in enumerate(MONTHS)}
def predict(region,crop,year,month,altitude,farm,fertilizer,seed,pest,soil,labor,distance):
 start=NUM[month]; names=[MONTHS[(start-1+i)%12] for i in range(4)]; w=W[(W.region==region)&(W.year==int(year))&W.month.isin(names)]; row=pd.DataFrame([{"region":region,"crop_type":crop,"survey_year":int(year),"planting_month":month,"altitude_m":float(altitude),"rainfall_mm_season":np.nan,"farm_size_ha":float(farm),"fertilizer_kg_per_ha":float(fertilizer),"improved_seed_used":int(seed),"pest_disease_flag":int(pest),"soil_quality_index":float(soil),"labor_days_per_ha":float(labor),"distance_to_market_km":float(distance),"season_mean_temp":w.avg_temp_c.mean(),"season_rainfall_mm":w.monthly_rainfall_mm.sum(),"season_extreme_heat_days":w.extreme_heat_days.sum(),"weather_months_observed":len(w),"season_temp_std":w.avg_temp_c.std(ddof=0),"season_rainfall_std":w.monthly_rainfall_mm.std(ddof=0),"season_temp_anomaly":np.nan,"planting_month_num":NUM[month],"fertilizer_seed_interaction":float(fertilizer)*int(seed),"rainfall_reporting_ratio":np.nan,"temp_rainfall_interaction":w.avg_temp_c.mean()*np.log1p(w.monthly_rainfall_mm.sum())}]); z=pd.get_dummies(row,columns=["region","crop_type","planting_month"],dtype=float).reindex(columns=COLS,fill_value=0); pred=float(MODEL.predict(z)[0]); price=float(P[(P.region==region)&(P.crop_type==crop)&(P.year==int(year))].price_birr_per_quintal.iloc[0]); rev=pred*float(farm)*10*price; ref=TRAIN[(TRAIN.region==region)&(TRAIN.crop_type==crop)].yield_tons_per_ha.mean(); return f"Predicted yield: {pred:.2f} tons/ha\nEstimated revenue: {rev:,.0f} birr\nLooked up: {w.avg_temp_c.mean():.1f} °C seasonal mean, {w.monthly_rainfall_mm.sum():.1f} mm seasonal rainfall, {price:,.0f} birr/quintal price\nReference region × crop mean: {ref:.2f} tons/ha"
regions=sorted(TRAIN.region.unique());crops=sorted(TRAIN.crop_type.unique())
with gr.Blocks(title="Qiyas Crop Yield Forecast") as demo:
 gr.Markdown("# Ethiopian Smallholder Crop-Yield Forecast")
 with gr.Row(): region=gr.Dropdown(regions,label="Region");crop=gr.Dropdown(crops,label="Crop type");year=gr.Dropdown([2021,2022,2023,2024],value=2024,label="Year");month=gr.Dropdown(["Feb","Mar","Jun","Jul","Aug"],value="Jun",label="Planting month")
 with gr.Row(): altitude=gr.Number(1500,label="Altitude (m)");farm=gr.Number(1,label="Farm size (ha)");fertilizer=gr.Number(40,label="Fertilizer (kg/ha)");soil=gr.Number(.6,label="Soil quality (0–1)")
 with gr.Row(): seed=gr.Radio([0,1],value=1,label="Improved seed");pest=gr.Radio([0,1],value=0,label="Pest/disease flag");labor=gr.Number(40,label="Labor days/ha");distance=gr.Number(10,label="Distance to market (km)")
 b=gr.Button("Predict yield");out=gr.Textbox(lines=5,label="Prediction");b.click(predict,[region,crop,year,month,altitude,farm,fertilizer,seed,pest,soil,labor,distance],out)
 gr.Markdown("Weather and price are looked up automatically. Price is not a yield-model feature.")
if __name__=="__main__": demo.launch()
